namespace RegistrationSystem.Core.Domain.NiqabBypasses;

/// <summary>
/// Represents an approved niqab bypass for a specific competitor.
/// Generated by admin, used once by the competitor to bypass face detection.
/// </summary>
public class NiqabBypass
{
    /// <summary>
    /// Unique identifier (MongoDB ObjectId).
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Competitor's first name (case-insensitive match).
    /// </summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Competitor's last name (case-insensitive match).
    /// </summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Competitor's date of birth.
    /// </summary>
    public DateOnly DateOfBirth { get; set; }

    /// <summary>
    /// 5-character alphanumeric code for the bypass URL.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Whether this bypass has been used.
    /// </summary>
    public bool IsUsed { get; set; }

    /// <summary>
    /// When this bypass was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Admin who created this bypass.
    /// </summary>
    public string? CreatedBy { get; set; }

    /// <summary>
    /// When this bypass was used (if used).
    /// </summary>
    public DateTimeOffset? UsedAt { get; set; }

    /// <summary>
    /// Competition year this bypass is valid for.
    /// </summary>
    public int CompetitionYear { get; set; }

    /// <summary>
    /// Optional notes from admin.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Matched registration ID (persisted after auto-sync).
    /// </summary>
    public string? RegistrationId { get; set; }

    /// <summary>
    /// Matched registration CID (persisted after auto-sync).
    /// </summary>
    public string? RegistrationCid { get; set; }

    /// <summary>
    /// True when created as a reverse bypass from photo review.
    /// AI detected a face through niqab — documenting for in-person identity verification.
    /// </summary>
    public bool IsReverse { get; set; }

    /// <summary>
    /// Generates a random 5-character alphanumeric code.
    /// </summary>
    public static string GenerateCode()
    {
        const string chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // Excluding confusing chars: I, O, 0, 1
        var random = new Random();
        return new string(Enumerable.Range(0, 5)
            .Select(_ => chars[random.Next(chars.Length)])
            .ToArray());
    }

    /// <summary>
    /// Checks if this bypass matches the given competitor info.
    /// </summary>
    public bool MatchesCompetitor(string firstName, string lastName, DateOnly dateOfBirth)
    {
        return string.Equals(FirstName.Trim(), firstName.Trim(), StringComparison.OrdinalIgnoreCase)
            && string.Equals(LastName.Trim(), lastName.Trim(), StringComparison.OrdinalIgnoreCase)
            && DateOfBirth == dateOfBirth;
    }

    /// <summary>
    /// Marks this bypass as used.
    /// </summary>
    public void MarkAsUsed()
    {
        IsUsed = true;
        UsedAt = DateTimeOffset.UtcNow;
    }
}